### PR TITLE
libretro: allow mingw cross compile

### PR DESCRIPTION
**Pull request by webgeek1234**

### CODE REVIEW

**Comment by leiradel** [comment]
Cross-compilation targetting Windows from a Linux host is achieved with the `Makefile.windows_x86` and `Makefile.windows_x86_64` makefiles. Is that what this PR is about?

**Comment by webgeek1234** [comment]
Yeah, it is. I didn't even look in those makefiles, though. I'd assumed they were msvc or something native only. Mingw is the cross compiler in use. I'll tweak my ci scripts to call into those and close this if it works.

**Comment by leiradel** [comment]
Yeah, the file names are very misleading. I'll leave it for you to close this PR if those makefiles work for you.

**Comment by webgeek1234** [comment]
Yeah, it works. Not entirely a fan of hardcoding all the compiler vars, but it does the job.

**Comment by leiradel** [comment]
I could define the toolchain with `?=`. Do you think its preferable?

**Comment by webgeek1234** [comment]
Yeah. I'm pushing changes like that to all the active libretro cores. So cross compile toolchains can pass in their own compilers. Like on Fedora, the mingw packages have mingw{32,64}-make, which define full paths to the right toolchain.

**Comment by leiradel** [comment]
These makefiles are generated from [here](https://github.com/leiradel/cross-makefiles), so if you could make the PRs to that repository instead it would be super.

**Comment by webgeek1234** [comment]
I'll skip the ones with those style makefiles and look at that later. That's like ten out of the hundred repos I'm going through atm, though.

**Pull request closed without merging**
